<a href="https://colab.research.google.com/github/bnanik/MNIST_TF/blob/main/MNIST_Prediction_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, relu, sigmoid
# %matplotlib widget
import matplotlib.pyplot as plt
# plt.style.use('./deeplearning.mplstyle')

import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

# from public_tests import * 

# from autils import *
# from lab_utils_softmax import plt_softmax
np.set_printoptions(precision=2)

In [13]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [ ]:
print ('The first element of X is: ', x_train[0])

In [18]:
print ('The first element of y is: ', y_train[0])


The first element of y is:  5


In [27]:
x_train = x_train.reshape(60000, 784)

In [28]:
print ('The shape of X is: ' + str(x_train.shape))
print ('The shape of y is: ' + str(y_train.shape))

The shape of X is: (60000, 784)
The shape of y is: (60000,)


In [21]:
tf.random.set_seed(1234)
model = Sequential(
    [
        tf.keras.Input(shape = (784)),
        Dense(25, activation = 'relu', name = 'L1'),
        Dense(15, activation = 'relu', name = 'L2'),
        Dense(10, activation = 'linear', name = 'L3')
    ], name = 'my_model'
)

In [22]:
model.summary()

Model: "my_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 25)                19625     
                                                                 
 L2 (Dense)                  (None, 15)                390       
                                                                 
 L3 (Dense)                  (None, 10)                160       
                                                                 
Total params: 20,175
Trainable params: 20,175
Non-trainable params: 0
_________________________________________________________________


In [23]:
[layer1, layer2, layer3] = model.layers

In [24]:
W1, b1 = layer1.get_weights()
W2, b2 = layer2.get_weights()
W3, b3 = layer3.get_weights()
print(f"W1 shape = {W1.shape}, b1 shape = {b1.shape} ")
print(f"W2 shape = {W2.shape}, b2 shape = {b2.shape} ")
print(f"W3 shape = {W3.shape}, b3 shape = {b3.shape} ")

W1 shape = (784, 25), b1 shape = (25,) 
W2 shape = (25, 15), b2 shape = (15,) 
W3 shape = (15, 10), b3 shape = (10,) 


In [39]:
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy']
)

history = model.fit(
    x_train, y_train,
    epochs=30
)

Epoch 1/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2285 - accuracy: 0.9347
Epoch 2/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2253 - accuracy: 0.9357
Epoch 3/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2244 - accuracy: 0.9358
Epoch 4/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2225 - accuracy: 0.9359
Epoch 5/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2202 - accuracy: 0.9375
Epoch 6/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2201 - accuracy: 0.9362
Epoch 7/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2178 - accuracy: 0.9371
Epoch 8/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2141 - accuracy: 0.9388
Epoch 9/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2118 - accuracy: 0.9386
Epoch 10/30
1875/1875 [==============================] - 4s 2ms/step - loss: 0.212

In [40]:
prediction = model.predict(x_test[1].reshape(1, 784))

print (prediction)
print(np.argmax(prediction))

[[-14.21  -0.87   5.78 -10.21 -18.72 -16.38  -6.49  -2.9  -19.3  -51.63]]
2


In [41]:
prediction_p = tf.nn.softmax(prediction)
prediction_p

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[2.09e-09, 1.29e-03, 9.99e-01, 1.13e-07, 2.28e-11, 2.38e-10,
        4.69e-06, 1.70e-04, 1.28e-11, 1.17e-25]], dtype=float32)>

In [42]:
yhat = np.argmax(prediction_p)
yhat

2

In [43]:
x_test.shape

(10000, 784)

In [44]:
x_test = x_test.reshape(10000, 784)
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.2968 - accuracy: 0.9240 - 480ms/epoch - 2ms/step


[0.29676175117492676, 0.9240000247955322]